# Generated by Django 4.2 on 2026-02-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="業務分類名")),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="会社名・氏名")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="連絡先"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="特記事項")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="案件名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未着手"),
                            ("in_progress", "進行中"),
                            ("checking", "確認中"),
                            ("completed", "完了"),
                            ("billed", "請求済"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="進捗状況",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="報酬額")),
                ("deadline", models.DateField(verbose_name="納期")),
                ("note", models.TextField(blank=True, verbose_name="フリーメモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.client",
                        verbose_name="クライアント",
                    ),
                ),
            ],
            options={
                "ordering": ["deadline"],
            },
        ),
    ]
